# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-17 09:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myoa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xinhurecord',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='xinhutodo',
            options={'managed': False},
        ),
    ]
