# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-17 09:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myoa', '0002_auto_20180617_0914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xinhurecord',
            options={'managed': True},
        ),
    ]
