# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-13 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='qq',
            field=models.CharField(help_text='请输入qq', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(help_text='<a href="password">修改密码<a/>', max_length=128, verbose_name='password'),
        ),
    ]
